import { Injectable } from '@angular/core';

@Injectable()
export class UsuariosService {
  clientes

  constructor() {
    this.clientes = [
      'Adolfo Nicolás',
      'Adolfo Pérez Esquivel',
      'Adolfo Ranero',
      'Adriana Guevara',
      'África de la Cruz',
      'Agencia de Noticias Prensa Ecuménica',
      'Agencia EFE',
      'Agencia Fides',
      'Agustí Cortés Soriano',
      'Agustín Goikoetxea',
      'Agustín Udías Vallina',
      'Alberto Giráldez',
      'Alberto Moncada',
      'Alejandro Córdoba',
      'Alejandro Fernández',
      'Alfredo Leuco',
      'Alfredo Sepúlveda',
      'Alto Comisionado de la ONU',
      'Álvaro de Juana',
      'Alver Metalli',
      'Amanda Céspedes',
      'Amnistía Internacional',
      'Amy Goodman y Juan González',
      'Ana Cabirta',
      'Ana Sofía Pérez-Bustamante',
      'Andrea Hojman',
      'Andrea Tornielli',
      'Andrés Aberasturi',
      'Andrés Torres Queiruga',
      'Ángel Arnaiz Quintana',
      'Ángel García-Zamorano',
      'Ángel Vilariño',
      'Ángela Murillo',
      'Ángeles Caso',
      'Ángeles Conde',
      'Anne Thomas y Yuka',
      'Anniken Jørgensen',
      'Anselmo Álvarez',
      'Anthony de Mello',
      'Antonio Aradillas',
      'Antonio Duato',
      'Antonio Esquivias',
      'Antonio García Polo',
      'Antonio Gil de Zúñiga',
      'Antonio Salas',
      'Ariel Álvarez Valdés',
      'Arnaldo Zenteno',
      'Asociación de Teólogas Españolas (Ate)',
      'Asociación de teólogos y teólogas Juan XXIII',
      'Asociación Foro Religioso Popular de Vitoria',
      'Asunción Poudereux',
      'Atrio',
      'Augusto Monterroso',
      'Augusto Zamora',
      'Aurelio Lepe',
      'Autor desconocido',
      'Bárbara Torres',
      'Beatriz Uriarte y Rosa Lago',
      'Benedicto XVI',
      'Benjamín Forcano',
      'Bernard Trémel',
      'Bernardo Marín y Alejandra Agudo',
      'Bernardo Pérez Andreu',
      'Beto Vargas',
      'Blanca Arregui',
      'Blas Lara',
      'Brahma Kumaris',
      'Braulio Hernández',
      'Bruno Álvarez',
      'Cameron Doody',
      'Camilo MACISSE',
      'Cáritas Española',
      'Cáritas, CONFER, el Sector Social de la Compañía de Jesús y Justicia y Paz',
      'Carles Capdevila',
      'Carlo Maria Martini',
      'Carlos A. Vallés',
      'Carlos Aizpurua',
      'Carlos Ayala Ramírez',
      'Carlos del Castillo',
      'Carlos Escudero Freire',
      'Carlos F. Barberá',
      'Carlos Fresneda',
      'Carlos López',
      'Carlos Prieto',
      'Carlos Sánchez Mato',
      'Carmen Almansa',
      'Carmen Bellver',
      'Carmen Charo',
      'Carmen Herrero',
      'Carmen Ilabaca',
      'Carmen Morán',
      'Carmen Notario',
      'Carmen Soto',
      'Carmiña Navia',
      'Carolina Abarca',
      'Carta de la Tierra',
      'Celso Alcaina',
      'César Cervera',
      'Christian de Chergé',
      'Christoph Strack',
      'Clara Janés',
      'Claude Benoit',
      'Claude Lacaille',
      'Claudio Fabián Guevara',
      'Clausura de la JMJ',
      'Comité Africa Negra Madrid - UMOYA',
      'Comunicado conjunto religiones',
      'Comunidad de Nazaret',
      'Comunidad de Sta. Rosa',
      'Comunidad Islámica de España',
      'Comunidad STA',
      'Comunidades Cristianas de América Latina',
      'Congreso continental de Teología',
      'Consuelo Vélez',
      'Crismhom',
      'Cristián Warnken',
      'Cristianismo y justicia',
      'Cristina Corte',
      'Cristina Fontenele',
      'Cristina Plaza',
      'Cristina Sánchez',
      'Curas Obreros de Europa',
      'Daniel Gomis',
      'Daniel Jarreta',
      'Daniel Ozuna',
      'Darío Menor',
      'David Bollero',
      'David Cano Martínez',
      'David Jiménez',
      'David Jou',
      'Deme Orte',
      'Desmond Tutu',
      'Diamuid O´Murchu',
      'Dolores Aleixandre',
      'Dolores Cabezudo',
      'Dolores López Guzmán',
      'Ecclesia',
      'Eckhart Tolle',
      'Eclesalia',
      'Edgard R. Beltrán',
      'Editorial del Diario de Noticias',
      'Eduard Punset',
      'Eduardo Arens',
      'Eduardo de la Serna',
      'Eduardo Galeano',
      'Eduardo Hornaert',
      'Eileen Markey',
      'El confidencial',
      'El Proyecto Matríz',
      'Elena Cué',
      'Elena Pita',
      'Elena Rodríguez-Avial',
      'Elisa Silió',
      'Elisabetta Piqué',
      'Eloy Roy',
      'Emilia Robles',
      'Emiliano Calle',
      'Emilio Carrillo',
      'Emilio Rodríguez',
      'Emma Martínez Ocaña',
      'Emma Torralba',
      'Encuentro latinoamericano',
      'Enric González',
      'Enrique Delgado',
      'Enrique Jaramillo Levi',
      'Enrique Martínez Lozano',
      'Esposas curas católicos',
      'Esteban Tabares',
      'Esteban Velázquez',
      'Eubilio Rodríguez',
      'Eugenio Scalfari',
      'Eusebio Losada',
      'Evaristo Fernández de Vega',
      'Evaristo Villar',
      'Eventos de Madrid y Sevilla',
      'Evo Morales Ayma',
      'F. Brune',
      'Fabián García',
      'Faustino Vilabrille',
      'Fe Adulta',
      'Federico García Lorca',
      'Feliciano Mayorga Tarriño',
      'Felipe Arizmendi Esquivel',
      'Félix Azurmendi',
      'Felix Jiménez Tutor',
      'Félix Placer Ugarte',
      'Feminists for Life of America',
      'Ferdinando Sudati',
      'Fernando Acín',
      'Fernando Baeta',
      'Fernando Bermúdez López',
      'Fernando Bermúdez López y Juan V. Fernández de la Gala',
      'Fernando Gamboa',
      'Fernando Lázaro',
      'Fernando Torres Pérez',
      'Fernando Trías de Bes',
      'Ferran Sales',
      'Fidel Aizpurúa',
      'Florentino Ulibarri',
      'Foro “Curas de Madrid”',
      'Fran Otero',
      'Francesc Escribano',
      'Francesc Mateu',
      'Francesc Torralba',
      'Francisco Asensi',
      'Francisco Ayala',
      'Francisco Bautista',
      'Francisco Margallo',
      'Francisco Massó',
      'Francisco Puértolas',
      'Francisco Rafael de Pascual',
      'François Houtart',
      'Fray Marcos',
      'Frei Betto',
      'Fundación Ananta',
      'Future Church',
      'Gabriel Asenjo',
      'Gabriel García de Oro',
      'Gabriel Mª Otalora',
      'Gabriela Mistral',
      'George R. Porta',
      'Gerardo Villar',
      'Giancarlo Pani',
      'Gilberto Urrutia',
      'Gloria Fuertes',
      'Gonzalo Fanjul',
      'Gonzalo Haya',
      'Grupo de cristianos de Navarra',
      'Grupo de curas argentinos',
      'Grupo Inmigración y Sistema Penal',
      'Grupo sacerdotal Enrique Angelelli y otros',
      'Guillermo Oroz Aragón',
      'Gustavo Duch',
      'Gustavo J. Magdalena',
      'Gustavo Valls',
      'Hans Küng',
      'Helen Groome',
      'Henri Boulad',
      'Henrique Mariño',
      'Hermana Juventany',
      'Hilari Raguer',
      'Honorio Cadarso',
      'Hospitalidad.es',
      'Humanismo Sin credos',
      'Ibn ‘Arabi',
      'Ibrahima',
      'Idoya Noian',
      'Iglesia Católica Colombiana',
      'Ignacio Ramonet',
      'Ignacio Trueba y Andrew McMillan',
      'Ignacio Villota',
      'Ima Sanchís',
      'Informe de la FAO',
      'Ínigo García',
      'Inma Calvo Torrejón',
      'Inma Eibe',
      'Intermón Oxfam',
      'Irene Hernández Velasco',
      'Irene Meca Mateo',
      'Irina Santesteban',
      'Isabel Gómez-Acebo',
      'Isidoro García',
      'Ismael Bárcenas Orozco',
      'J. A. Estrada',
      'J. Agustín Franco',
      'J. Jesús Lemus',
      'J. Morán',
      'J. Subercaseaux',
      'J. V. Echagüe',
      'Jaime Escobar',
      'Jaime Rubio Hancock',
      'Jairo del Agua',
      'Jan Martínez Ahrens',
      'Javier Domínguez',
      'Javier Elzo',
      'Javier Gomá Lanzón',
      'Javier Lozano',
      'Javier Marín',
      'Javier Melloni',
      'Javier Monserrat',
      'Javier Pagola',
      'Javier Salas',
      'Javier Velasco',
      'Javier Vitoria',
      'Jean de Dieu Tagne',
      'Jeff Foster',
      'Jesuitas',
      'Jesús Bastante',
      'Jesús Díaz Gómez',
      'Jesús Espeja',
      'Jesús Gil García',
      'Jesús Hidalgo',
      'Jesús Mª Urío',
      'Jesús Martínez',
      'Jesús Sanz',
      'Jesús Trillo',
      'Joan Carrera',
      'Joan Chittister',
      'Joaquín Sempere',
      'Joaquín Solá Martínez',
      'John P. Meier',
      'John Shelby Spong',
      'Jon Sobrino',
      'Jorge Alcalde',
      'Jorge Costadoat',
      'Jorge Eduardo Lozano',
      'Jorge Oyhanarte',
      'Jorge Serrano',
      'José Agustín Cabré',
      'José Agustín Maroto',
      'José Aldunate',
      'José Alegre',
      'José Antonio Marina',
      'José Antonio Pagola',
      'José Antonio Revuelta',
      'José Arregi',
      'José Carlos Enríquez',
      'José Comblin',
      'José Cristo Rey',
      'José de Segovia',
      'José Enrique Galarreta [†]',
      'José Ignacio Calleja',
      'José Ignacio González Faus',
      'José Ignacio Munilla',
      'José Ignacio Spuche',
      'José Juan Toharia',
      'José Luís Aníbal Battellino',
      'José Luís Caravias',
      'José Luis Ferrando Lada',
      'José Luis Martín Descalzo',
      'José Luís Palacios',
      'José Luis Perera López',
      'José Luis Pinilla',
      'José Luis Sicre',
      'José Luis Vázquez',
      'José Luís Vilanova Alonso',
      'José M. Castillo',
      'José M. Peiro Alba',
      'José Mª Rivas Conde',
      'José Manuel Bernal',
      'José Manuel Caamaño',
      'José Manuel Vidal',
      'José María Alonso Rico',
      'José María Álvarez',
      'José María Arnaiz',
      'José María Díez Alegría',
      'José María García-Mauriño',
      'José María Mardones [†]',
      'José María Martín Patino',
      'José María Toro',
      'José Miguel Izquierdo',
      'José Moreno',
      'José Mujica',
      'José Olivero',
      'José Ramón Scheiffler',
      'José Rodríguez Carballo',
      'José Sánchez Luque',
      'José Saramago',
      'Josean Villalabeitia',
      'Josep Miquel Bausset',
      'Juan Antonio Herrero Brasas',
      'Juan Arias',
      'Juan Cejudo',
      'Juan Cruz',
      'Juan G. Bedoya',
      'Juan Jauregui',
      'Juan José Aguirre',
      'Juan José Arnáiz',
      'Juan José Mateo',
      'Juan José Omella',
      'Juan José Tamayo',
      'Juan Lara',
      'Juan Luís Herrero del Pozo',
      'Juan Manuel de Prada',
      'Juan Martín Velasco',
      'Juan Masiá',
      'Juan Miguel Zuñiga y Javier Oñate',
      'Juan Morera Peralta',
      'Juan P. Espinosa Arce',
      'Juan Ramón Lacadena',
      'Juan Rubio',
      'Juan Torres López',
      'Juan V. Fernández de la Gala',
      'Juan Yzuel',
      'Juan Zapatero',
      'Juanjo Aguado',
      'Juantxu Oscoz',
      'Judith Martínez',
      'Julián Mellado',
      'Jung Mo Sung',
      'Karibu',
      'Karl Rahner',
      'Kelly Velázquez',
      'Ken Wilber',
      'Khalil Gibrain',
      'Koldo Aldai',
      'Koldo Campos Sagaseta',
      'Kuczynski',
      'L.J. Lebret',
      'La Marea',
      'La Razón',
      'La vía campesina',
      'Laura Serrano-Conde',
      'LCWR',
      'Leandro Sequeiros',
      'León Felipe',
      'Leonardo Boff',
      'Leonardo Gonzalbes',
      'Leopoldo Abadía',
      'Leopoldo Diez de Fortuny',
      'Libio Pérez',
      'Lluís Bassets',
      'Lucia Gayón',
      'Lucía López Alonso',
      'Luigi de Paoli',
      'Luís Alemán',
      'Luis Ángel Aguilar',
      'Luís Bruschtein',
      'Luís Cano',
      'Luís Carlos Saiz Fernández',
      'Luís García Montero',
      'Luís García Orso',
      'Luis Miguel Baronetto',
      'Luis Miguel Modino',
      'M. Arrizabalaga',
      'Mª Ángeles López Romero',
      'Mª Carmen Ferrero',
      'Mª Carmen Nieto León',
      'Macarena y Dan',
      'Mads Gilbert',
      'Magdalena Bennasar',
      'Maite García Romero',
      'Manfred Max-Neef',
      'Manuel Ansede',
      'Manuel Calvo Beca',
      'Manuel González',
      'Manuel Reyes Mate',
      'Marciano Vidal',
      'Marco Antonio Velásquez Uribe',
      'Margarita Pintos',
      'Mari Enrique Belvis',
      'Mari Patxi Ayerra',
      'Mari Paz López Santos',
      'Mariá Corbí',
      'Maria López Vigil',
      'María Mikhailova',
      'María Pérez',
      'María Teresa Sánchez Carmona',
      'María y José Ignacio López Vigil',
      'Mariana Caplan',
      'Mariano Martínez',
      'Marifé Ramos',
      'Mariló Hidalgo',
      'Mario Benedetti',
      'Mario González',
      'Mariola López Villanueva',
      'Marisa Noriega',
      'Marta García',
      'Marta Ríos',
      'Martín Gelabert Ballester',
      'Martín Pérez Millán',
      'Matías Vallés',
      'Matilde Garzón Ruipérez',
      'Matilde Gastalver',
      'Mercedes Nasarre',
      'Michel Quoist',
      'Miguel Ángel Mesa',
      'Miguel Ángel Munárriz Casajús',
      'Miguel d’Escoto',
      'Miguel Esquirol Vives',
      'Miryam Castro',
      'Misión Joven',
      'MOCEOP',
      'Mónica Cavallé',
      'Movimiento Monseñor Gerardi',
      'Muhammad Yunus',
      'Mujeres y Teología de Ciudad Real',
      'Mussa’ab Bashir',
      'Nabil Antaki',
      'Nacho Dueñas',
      'Naiara Galarraga',
      'Nani Vall-llossera',
      'Natalia Martín',
      'Nelly Arrobo Rodas',
      'Nestor Nongo',
      'Nicolás Castellanos Franco',
      'Nicolás Lafferriere',
      'Nicolás Pons',
      'Nicole Muchnik',
      'Nilamben Parikh Gandhi',
      'Norberto Levy',
      'Obispos catacumba de Santa Domitila',
      'Obispos congoleños',
      'Olga Larrazábal',
      'Óscar Gutiérrez',
      'Óscar Mateos',
      'Óscar Salazar',
      'P. Unamuno',
      'Pablo Drs',
      'Pablo Domínguez',
      'Pablo Jáuregui',
      'Pablo Moñino',
      'Pablo Ordaz',
      'Padre Ángel García',
      'Padres de Maryknoll',
      'Papa Francisco',
      'Paquita Reche',
      'Parroquia St. Joan Evangelista',
      'Participantes del VIII Encuentro Latinoamericano y Caribeño de CEBs',
      'Pastoral penitenciaria',
      'Pastoralsj.org',
      'Patricia Paz',
      'Patxi Aizpitarte',
      'Patxi Loidi',
      'Paul Lafargue',
      'Paula Depalma',
      'Pedro Aranda',
      'Pedro Casaldáliga',
      'Pedro Emilio Ramírez',
      'Pedro Kalmbach',
      'Pedro Miguel Lamet',
      'Pedro Olalde',
      'Pedro Ontoso',
      'Pedro Zabala',
      'Peio Sánchez',
      'Pepa Torres',
      'Pepcastelló',
      'Pepe Álvarez de las Asturias',
      'Pepe Baena',
      'Pepe Laguna',
      'Pere Codina Mas',
      'Philippe Ariño',
      'Pilar Rahola',
      'Plataforma por la Justicia Fiscal',
      'Plataforma Salvemos la hospitalidad',
      'Pope Godoy',
      'Rabino Abraham Skorka',
      'Rafa Rodrigo Ferrandis',
      'Rafael Argullol',
      'Rafael Calvo Beca',
      'Rafael Díaz Arias',
      'Rafael Fernando Navarro',
      'Ramón Alario y Julio Pinillos',
      'Ramón Almansa',
      'Raquel Pérez',
      'Raquel Simón Justo',
      'Raúl Juárez',
      'Rebeca Yanke y Joaquin Vera',
      'Redacción de Alandar',
      'Redacción Noticias Obreras HOAC',
      'Redes Cristianas',
      'Reflexión y Liberación (Chile)',
      'Religión Digital',
      'Religiosos de Gipuzkoa',
      'Religiosos y obispos paraguayos',
      'Resumen de agencias',
      'Resumen de prensa',
      'Rev. Mendelson Dávila A',
      'Ricardo Benjumea',
      'Ricardo Blázquez',
      'Ricardo Gayol',
      'Richard J. Roberts',
      'Roberto Alifano',
      'Roberto Savio',
      'Rogelio Cárdenas',
      'Román Espadas',
      'Rosa M. Tristán',
      'Roy Bourgeois',
      'Rufo González',
      'Rupert Spira',
      'Sacerdotes austríacos',
      'Salomé Arricibita',
      'Salvador Capote',
      'Salvador G. Figueras',
      'Salvador Mendoza',
      'Salvador Sostres',
      'Samir Khalil Samir',
      'Sandra Hojman',
      'Santi Torres',
      'Santiago Agrelo',
      'Santiago Panizo',
      'Santiago Sánchez Torrado',
      'Santiago Villamayor',
      'Saturnino Rodríguez',
      'Sergio Bergman',
      'Sergio Sinay',
      'Sonia Fernández-Vidal',
      'Sor María de Gracia',
      'Stella Maris Maruso',
      'Stephen Evans',
      'Susana Hidalgo',
      'Susana Merino',
      'Teilhard de Chardin',
      'Teófilo Cabestrero',
      'Teología y Pastoral Andina',
      'Tere Cortés',
      'Teresa de Calcuta',
      'Teresa Forcades',
      'Tino Fernández',
      'Tomás Maza Ruiz',
      'Tomás Muro',
      'Tomás Trigo',
      'Un experimento científico con monos',
      'Valerio Gigante',
      'Varios autores',
      'Vicenc Alujas',
      'Vicente Gallego',
      'Vicente Jiménez',
      'Vicente Martínez',
      'Vicente Romero',
      'Vicente Simón',
      'Vicky Irigaray',
      'Víctor Codina',
      'Víctor Daniel Blanco',
      'Víctor Frankl',
      'Víctor Hugo',
      'Víctor M. Amela',
      'Victoria Juliani',
      'Voces cristianas de Sevilla',
      'Walter Kasper',
      'Willigis Jäger',
      'www.humus.tk',
      'Xavier Caño Tamayo',
      'Xavier Casanovas',
      'Xavier Guix',
      'Xavier Pikaza',
      'XVII Semana Andaluza de Teología',
      'Yerachmiel Tilles',
      'Yolanda Chávez',
      'Yolanda Plaza Ruíz'
    ];
  }

}
